dist: xenial
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11
  - openjdk11
#  - oraclejdk7
#  - openjdk7
#  - openjdk6

script:
  "./gradlew check -i"

addons:
  hosts:
    - mocobuild
  hostname: mocobuild